version: '3.8'
    services:
      postgres:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: messengerdb
        ports:
          - '5432:5432'
        volumes:
          - postgres_data:/var/lib/postgresql/data

      backend:
        build: ./backend
        ports:
          - '3000:3000'
        depends_on:
          - postgres
        environment:
          DATABASE_URL: postgres://user:password@postgres:5432/messengerdb
        volumes:
          - ./backend:/usr/src/app
          - /usr/src/app/node_modules

      frontend:
        build: ./frontend
        ports:
          - '5173:5173'
        depends_on:
          - backend
        volumes:
          - ./frontend:/usr/src/app
          - /usr/src/app/node_modules

    volumes:
      postgres_data:
